package cc.khixang.axonhub.ui

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.verticalScroll
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalUriHandler
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.unit.dp
import cc.khixang.axonhub.AxonHubApplication
import cc.khixang.axonhub.core.*
import cc.khixang.axonhub.gateway.ChannelTypes
import coil3.compose.AsyncImage
import kotlinx.coroutines.launch
import kotlinx.serialization.json.*

@Composable fun GatewayScreen(app: AxonHubApplication) {
    val state by app.repository.snapshot.collectAsState(); var models by remember { mutableStateOf(false) }; var search by remember { mutableStateOf("") }
    var channelEditor by remember { mutableStateOf<JsonElement?>(null) }; var modelEditor by remember { mutableStateOf<JsonElement?>(null) }; var detail by remember { mutableStateOf<Pair<Boolean, String>?>(null) }
    val scope = rememberCoroutineScope()
    Column(Modifier.fillMaxSize().padding(16.dp)) {
        Row { Text("Gateway", style = MaterialTheme.typography.headlineMedium, modifier = Modifier.weight(1f)); IconButton({ if (models) modelEditor = JsonNull else channelEditor = JsonNull }) { Icon(Icons.Default.Add, "Create") }; IconButton({ scope.launch { app.repository.refresh() } }) { Icon(Icons.Default.Refresh, "Refresh") } }
        SingleChoiceSegmentedButtonRow(Modifier.fillMaxWidth()) { SegmentedButton(!models, { models = false }, SegmentedButtonDefaults.itemShape(0, 2)) { Text("Channels") }; SegmentedButton(models, { models = true }, SegmentedButtonDefaults.itemShape(1, 2)) { Text("Models") } }
        OutlinedTextField(search, { search = it }, label = { Text("Search") }, modifier = Modifier.fillMaxWidth())
        Spacer(Modifier.height(8.dp))
        when (val current = state) {
            LoadState.Idle, LoadState.Loading -> CircularProgressIndicator()
            is LoadState.Failed -> ErrorState(current.message) { scope.launch { app.repository.refresh() } }
            is LoadState.Ready -> if (models) {
                val rows = current.value.models.filter { search.isBlank() || it.name.contains(search, true) || it.modelId.contains(search, true) }
                LazyColumn(verticalArrangement = Arrangement.spacedBy(8.dp)) { items(rows, key = { it.id }) { item -> ElevatedCard(onClick = { detail = false to item.id }, Modifier.fillMaxWidth()) { Row(Modifier.padding(16.dp)) { ProviderBrand(item.developer); Spacer(Modifier.width(10.dp)); Column(Modifier.weight(1f)) { Text(item.name, style = MaterialTheme.typography.titleMedium); Text(item.modelId); Text("${item.developer} · ${item.type}", style = MaterialTheme.typography.bodySmall) }; StatusDot(item.status) } } } }
            } else {
                val rows = current.value.channels.filter { search.isBlank() || it.name.contains(search, true) || it.type.contains(search, true) }
                LazyColumn(verticalArrangement = Arrangement.spacedBy(8.dp)) { items(rows, key = { it.id }) { item -> ElevatedCard(onClick = { detail = true to item.id }, Modifier.fillMaxWidth()) { Row(Modifier.padding(16.dp)) { ProviderBrand(item.type); Spacer(Modifier.width(10.dp)); Column(Modifier.weight(1f)) { Text(item.name, style = MaterialTheme.typography.titleMedium); Text(item.type); Text("${item.supportedModels.size} models · weight ${item.orderingWeight}", style = MaterialTheme.typography.bodySmall) }; StatusDot(item.status) } } } }
            }
        }
    }
    detail?.let { (channel, id) -> GatewayDetailDialog(app, channel, id, onDismiss = { detail = null }, onEdit = { value -> if (channel) channelEditor = value else modelEditor = value }) }
    channelEditor?.let { value -> ChannelEditorDialog(app, value.takeUnless { it is JsonNull }, { channelEditor = null }) }
    modelEditor?.let { value -> ModelEditorDialog(app, value.takeUnless { it is JsonNull }, { modelEditor = null }) }
}

@Composable private fun StatusDot(status: String) { AssistChip({}, { Text(status.ifBlank { "unknown" }) }, leadingIcon = { Icon(if (status == "enabled") Icons.Default.CheckCircle else Icons.Default.PauseCircle, null) }) }

@Composable private fun ProviderBrand(raw: String) {
    val key = raw.lowercase().let { value -> when { "anthropic" in value || "claude" in value -> "anthropic"; "gemini" in value || "google" in value -> "gemini"; "deepseek" in value -> "deepseek"; "openrouter" in value -> "openrouter"; "xai" in value || "grok" in value -> "xai"; "github" in value || "copilot" in value -> "github"; "ollama" in value -> "ollama"; "openai" in value || "codex" in value -> "openai"; else -> "" } }
    if (key.isNotEmpty()) AsyncImage(model = "file:///android_asset/brand-icons/$key.png", contentDescription = null, modifier = Modifier.size(36.dp))
    else Icon(Icons.Default.Hub, null, modifier = Modifier.size(36.dp))
}

@Composable private fun GatewayDetailDialog(app: AxonHubApplication, channel: Boolean, id: String, onDismiss: () -> Unit, onEdit: (JsonElement) -> Unit) {
    var value by remember { mutableStateOf<JsonElement>(JsonNull) }; var error by remember { mutableStateOf<String?>(null) }; var busy by remember { mutableStateOf(false) }; var confirmDelete by remember { mutableStateOf(false) }; var test by remember { mutableStateOf<String?>(null) }; val scope = rememberCoroutineScope()
    fun load() { scope.launch { busy = true; try { value = if (channel) app.gateway.channelDetail(id) else app.gateway.modelDetail(id); error = null } catch (t: Throwable) { error = t.message } finally { busy = false } } }
    LaunchedEffect(id) { load() }
    AlertDialog(onDismissRequest = onDismiss, title = { Text(if (channel) value["name"].text.ifBlank { "Channel" } else value["name"].text.ifBlank { "Model" }) },
        text = { LazyColumn(Modifier.heightIn(max = 600.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) {
            if (busy) item { LinearProgressIndicator(Modifier.fillMaxWidth()) }; error?.let { item { Text(it, color = MaterialTheme.colorScheme.error) } }
            if (value !is JsonNull) {
                item { DetailFields(value, listOf("id", "name", "type", "status", "baseURL", "modelID", "developer", "group", "defaultTestModel", "orderingWeight", "supportedModels", "tags", "remark", "errorMessage")) }
                item { Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) { Button({ onEdit(value); onDismiss() }) { Icon(Icons.Default.Edit, null); Text("Edit") }; OutlinedButton({ scope.launch { busy = true; try { if (channel) app.gateway.setChannelEnabled(id, value["status"].text != "enabled") else app.gateway.setModelEnabled(id, value["status"].text != "enabled"); load() } finally { busy = false } } }) { Text(if (value["status"].text == "enabled") "Disable" else "Enable") } } }
                if (channel) item { Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) { OutlinedButton({ scope.launch { busy = true; try { val result = app.gateway.testChannel(id, value["defaultTestModel"].text); test = if (result.first) "Connected in ${result.second} ms" else "Connectivity test failed (upstream error hidden)." } catch (t: Throwable) { test = t.message } finally { busy = false } } }) { Text("Test") }; OutlinedButton({ scope.launch { busy = true; try { val list = app.gateway.syncModels(id, value["autoSyncModelPattern"].text.takeIf(String::isNotBlank)); test = "Synced ${list.size} models"; load() } catch (t: Throwable) { test = t.message } finally { busy = false } } }) { Text("Sync models") } }; test?.let { Text(it) } }
                item { TextButton({ confirmDelete = true }, colors = ButtonDefaults.textButtonColors(contentColor = MaterialTheme.colorScheme.error)) { Icon(Icons.Default.Delete, null); Text("Delete") } }
                item { HorizontalDivider(); Text("Advanced values", style = MaterialTheme.typography.titleMedium); DetailFields(value, value.obj.keys.filterNot { it in setOf("id", "name", "type", "status", "baseURL", "modelID", "developer", "group", "remark") }.sorted()) }
            }
        } }, confirmButton = { TextButton(onClick = onDismiss) { Text("Close") } })
    if (confirmDelete) AlertDialog(onDismissRequest = { confirmDelete = false }, title = { Text("Delete this ${if (channel) "channel" else "model"}?") }, text = { Text("This writes to the live server and cannot be undone.") }, confirmButton = { Button(colors = ButtonDefaults.buttonColors(containerColor = MaterialTheme.colorScheme.error), onClick = { scope.launch { try { if (channel) app.gateway.deleteChannel(id) else app.gateway.deleteModel(id); app.repository.refresh(); onDismiss() } catch (t: Throwable) { error = t.message }; confirmDelete = false } }) { Text("Delete") } }, dismissButton = { TextButton({ confirmDelete = false }) { Text("Cancel") } })
}

@Composable private fun ChannelEditorDialog(app: AxonHubApplication, initial: JsonElement?, onDismiss: () -> Unit) {
    val schema = app.adminCatalog.schema; var name by remember { mutableStateOf(initial["name"].text) }; var type by remember { mutableStateOf(initial["type"].text.ifBlank { "openai" }) }; var baseUrl by remember { mutableStateOf(initial["baseURL"].text) }; var models by remember { mutableStateOf(initial["supportedModels"].arr.joinToString("\n") { it.text }) }; var defaultModel by remember { mutableStateOf(initial["defaultTestModel"].text) }; var tags by remember { mutableStateOf(initial["tags"].arr.joinToString("\n") { it.text }) }; var weight by remember { mutableStateOf((initial["orderingWeight"].intOrNull ?: 0).toString()) }; var remark by remember { mutableStateOf(initial["remark"].text) }
    var settings by remember { mutableStateOf(initial["settings"].takeUnless { it is JsonNull } ?: buildJsonObject {}) }; var policies by remember { mutableStateOf(initial["policies"].takeUnless { it is JsonNull } ?: buildJsonObject { put("stream", "unlimited") }) }; var credentials by remember { mutableStateOf<JsonElement>(buildJsonObject {}) }; var apiKey by remember { mutableStateOf("") }; var authorized by remember { mutableStateOf(false) }; var oauth by remember { mutableStateOf(false) }; var busy by remember { mutableStateOf(false) }; var error by remember { mutableStateOf<String?>(null) }; val scope = rememberCoroutineScope()
    AlertDialog(onDismissRequest = { if (!busy) onDismiss() }, title = { Text(if (initial == null) "Create channel" else "Edit channel") }, text = { Column(Modifier.heightIn(max = 650.dp).verticalScroll(androidx.compose.foundation.rememberScrollState()), verticalArrangement = Arrangement.spacedBy(9.dp)) {
        OutlinedTextField(name, { name = it }, label = { Text("Name") }, modifier = Modifier.fillMaxWidth()); EnumDropdown("Provider", type, ChannelTypes.all) { type = it }; OutlinedTextField(baseUrl, { baseUrl = it }, label = { Text("Base URL") }, modifier = Modifier.fillMaxWidth()); OutlinedTextField(models, { models = it }, label = { Text("Supported models (one per line)") }, minLines = 3, modifier = Modifier.fillMaxWidth()); OutlinedTextField(defaultModel, { defaultModel = it }, label = { Text("Default test model") }, modifier = Modifier.fillMaxWidth()); OutlinedTextField(tags, { tags = it }, label = { Text("Tags (one per line)") }, modifier = Modifier.fillMaxWidth()); OutlinedTextField(weight, { weight = it }, label = { Text("Weight") }, modifier = Modifier.fillMaxWidth()); OutlinedTextField(remark, { remark = it }, label = { Text("Remark") }, modifier = Modifier.fillMaxWidth())
        Text("Policies", style = MaterialTheme.typography.titleMedium); SchemaValueEditor(schema, "ChannelPoliciesInput", policies, { policies = it }, "Policies")
        Text("Settings", style = MaterialTheme.typography.titleMedium); SchemaValueEditor(schema, "ChannelSettingsInput", settings, { settings = it }, "Settings")
        Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) { OutlinedButton({ scope.launch { busy = true; error = null; try { val input = buildJsonObject { put("channelType", type); put("baseURL", baseUrl.trim()); apiKey.takeIf(String::isNotBlank)?.let { put("apiKey", it) }; initial?.get("id")?.text?.takeIf(String::isNotBlank)?.let { put("channelID", it) } }; val found = app.gateway.fetchUpstreamModels(input); models = found.joinToString("\n") } catch (t: Throwable) { error = t.message } finally { busy = false } } }, enabled = !busy && baseUrl.isNotBlank()) { Text("Fetch models") }; if (type in setOf("codex", "claudecode", "antigravity", "xai_subscription", "github_copilot")) OutlinedButton({ oauth = true }) { Text("OAuth") } }
        if (initial != null && !authorized) OutlinedButton({ scope.launch { busy = true; try { val secret = app.gateway.channelSecrets(initial["id"].text); credentials = secret["credentials"]; apiKey = secret["credentials"]["apiKey"].text; settings = secret["settings"]; authorized = true } catch (t: Throwable) { error = t.message } finally { busy = false } } }) { Text("Authorize and load existing credentials") }
        OutlinedTextField(apiKey, { apiKey = it }, label = { Text(if (initial == null) "API key" else "API key (only sent when authorized)") }, visualTransformation = PasswordVisualTransformation(), modifier = Modifier.fillMaxWidth())
        error?.let { Text(it, color = MaterialTheme.colorScheme.error) }; if (busy) LinearProgressIndicator(Modifier.fillMaxWidth())
    } }, confirmButton = { Button(enabled = !busy, onClick = { scope.launch { busy = true; error = null; try { val line = { s: String -> s.lines().map(String::trim).filter(String::isNotEmpty).distinct() }; val draft = buildJsonObject { put("name", name.trim()); if (baseUrl.isNotBlank()) put("baseURL", baseUrl.trim()); put("type", type); put("supportedModels", JsonArray(line(models).map(::JsonPrimitive))); put("defaultTestModel", defaultModel.trim()); put("tags", JsonArray(line(tags).map(::JsonPrimitive))); put("orderingWeight", weight.toIntOrNull() ?: 0); put("remark", remark); put("policies", policies); put("settings", settings); if (apiKey.isNotBlank() || credentials.obj.isNotEmpty()) put("credentials", JsonObject(credentials.obj.toMutableMap().also { if (apiKey.isNotBlank()) it["apiKey"] = JsonPrimitive(apiKey.trim()) })) }; app.gateway.saveChannel(initial["id"].text.takeIf(String::isNotBlank), draft, initial ?: JsonNull, authorized || initial == null); app.repository.refresh(); onDismiss() } catch (t: Throwable) { error = t.message } finally { busy = false } } }) { Text("Save") } }, dismissButton = { TextButton(onClick = onDismiss) { Text("Cancel") } })
    if (oauth) OAuthDialog(app, type, settings["proxy"], { credential -> apiKey = credential; authorized = true; oauth = false }, { oauth = false })
}

@Composable private fun OAuthDialog(app: AxonHubApplication, channelType: String, proxy: JsonElement, imported: (String) -> Unit, dismiss: () -> Unit) {
    val provider = when (channelType) { "github_copilot" -> "copilot"; "xai_subscription" -> "xai"; else -> channelType }
    var session by remember { mutableStateOf("") }; var authUrl by remember { mutableStateOf("") }; var userCode by remember { mutableStateOf("") }; var callback by remember { mutableStateOf("") }; var importValue by remember { mutableStateOf("") }; var projectId by remember { mutableStateOf("") }; var busy by remember { mutableStateOf(false) }; var message by remember { mutableStateOf<String?>(null) }
    val scope = rememberCoroutineScope(); val uriHandler = LocalUriHandler.current
    fun run(action: String, body: JsonObject) { scope.launch { busy = true; message = null; try { val result = app.gateway.oauth(provider, action, body); if (action == "oauth/start") { session = result["session_id"].text; authUrl = if (provider == "copilot") result["verification_uri"].text else result["auth_url"].text; userCode = result["user_code"].text } else if (provider == "copilot" && result["access_token"].text.isNotBlank()) imported(buildJsonObject { put("access_token", result["access_token"].text); put("token_type", "bearer") }.toString()) else if (result["credentials"].text.isNotBlank()) imported(result["credentials"].text) else message = "Authorization is incomplete or expired." } catch (t: Throwable) { message = t.message } finally { busy = false } } }
    AlertDialog(onDismissRequest = { if (!busy) dismiss() }, title = { Text("Provider authorization") }, text = { Column(Modifier.heightIn(max = 620.dp).verticalScroll(androidx.compose.foundation.rememberScrollState()), verticalArrangement = Arrangement.spacedBy(9.dp)) {
        Text("Authorize on the provider page. Credentials are kept in memory and are only sent when you save the channel.", style = MaterialTheme.typography.bodySmall)
        if (provider == "antigravity") OutlinedTextField(projectId, { projectId = it }, label = { Text("Google Cloud project (optional)") }, modifier = Modifier.fillMaxWidth())
        Button(enabled = !busy, onClick = { run("oauth/start", buildJsonObject { if (provider == "antigravity" && projectId.isNotBlank()) put("project_id", projectId.trim()) }) }, modifier = Modifier.fillMaxWidth()) { Text("Start authorization") }
        if (authUrl.isNotBlank()) OutlinedButton({ runCatching { java.net.URI(authUrl) }.getOrNull()?.takeIf { it.scheme == "https" && it.userInfo == null && !it.host.isNullOrBlank() }?.let { uriHandler.openUri(it.toString()) } ?: run { message = "The provider returned an unsafe authorization URL." } }, Modifier.fillMaxWidth()) { Text("Open provider page") }
        if (userCode.isNotBlank()) Text(userCode, style = MaterialTheme.typography.titleMedium)
        if (provider == "copilot") OutlinedButton(enabled = session.isNotBlank() && !busy, onClick = { run("oauth/poll", buildJsonObject { put("session_id", session) }) }, modifier = Modifier.fillMaxWidth()) { Text("Check authorization status") }
        else { OutlinedTextField(callback, { callback = it }, label = { Text("Authorization callback URL") }, visualTransformation = PasswordVisualTransformation(), modifier = Modifier.fillMaxWidth()); OutlinedButton(enabled = session.isNotBlank() && callback.isNotBlank() && !busy, onClick = { run("oauth/exchange", buildJsonObject { put("session_id", session); put("callback_url", callback); if (proxy["type"].text == "URL") put("proxy", JsonObject(proxy.obj.toMutableMap().also { it["type"] = JsonPrimitive("url") })) }) }, modifier = Modifier.fillMaxWidth()) { Text("Import authorized credentials") } }
        if (provider == "codex" || provider == "xai") { OutlinedTextField(importValue, { importValue = it }, label = { Text(if (provider == "codex") "Codex auth.json" else "xAI SSO token") }, visualTransformation = PasswordVisualTransformation(), modifier = Modifier.fillMaxWidth()); OutlinedButton(enabled = importValue.isNotBlank() && !busy, onClick = { run(if (provider == "codex") "auth/decode" else "oauth/sso", buildJsonObject { put(if (provider == "codex") "auth_json" else "sso_token", importValue) }) }, modifier = Modifier.fillMaxWidth()) { Text("Parse and import") } }
        message?.let { Text(it, color = MaterialTheme.colorScheme.error) }; if (busy) LinearProgressIndicator(Modifier.fillMaxWidth())
    } }, confirmButton = {}, dismissButton = { TextButton(enabled = !busy, onClick = dismiss) { Text("Close") } })
}

@Composable private fun ModelEditorDialog(app: AxonHubApplication, initial: JsonElement?, onDismiss: () -> Unit) {
    val schema = app.adminCatalog.schema; var name by remember { mutableStateOf(initial["name"].text) }; var modelId by remember { mutableStateOf(initial["modelID"].text) }; var developer by remember { mutableStateOf(initial["developer"].text) }; var type by remember { mutableStateOf(initial["type"].text.ifBlank { "chat" }) }; var group by remember { mutableStateOf(initial["group"].text) }; var icon by remember { mutableStateOf(initial["icon"].text) }; var remark by remember { mutableStateOf(initial["remark"].text) }; var card by remember { mutableStateOf(initial["modelCard"].takeUnless { it is JsonNull } ?: schema.defaultValue("ModelCardInput!")) }; var settings by remember { mutableStateOf(initial["settings"].takeUnless { it is JsonNull } ?: schema.defaultValue("ModelSettingsInput!")) }; var busy by remember { mutableStateOf(false) }; var error by remember { mutableStateOf<String?>(null) }; val scope = rememberCoroutineScope()
    AlertDialog(onDismissRequest = onDismiss, title = { Text(if (initial == null) "Create model" else "Edit model") }, text = { Column(Modifier.heightIn(max = 650.dp).verticalScroll(androidx.compose.foundation.rememberScrollState()), verticalArrangement = Arrangement.spacedBy(9.dp)) { OutlinedTextField(name, { name = it }, label = { Text("Name") }, modifier = Modifier.fillMaxWidth()); OutlinedTextField(modelId, { modelId = it }, label = { Text("Model ID") }, modifier = Modifier.fillMaxWidth()); OutlinedTextField(developer, { developer = it }, label = { Text("Developer") }, modifier = Modifier.fillMaxWidth()); EnumDropdown("Type", type, listOf("chat", "embedding", "rerank", "image_generation", "video_generation")) { type = it }; OutlinedTextField(group, { group = it }, label = { Text("Group") }, modifier = Modifier.fillMaxWidth()); OutlinedTextField(icon, { icon = it }, label = { Text("Icon name") }, modifier = Modifier.fillMaxWidth()); OutlinedTextField(remark, { remark = it }, label = { Text("Remark") }, modifier = Modifier.fillMaxWidth()); Text("Model card", style = MaterialTheme.typography.titleMedium); SchemaValueEditor(schema, "ModelCardInput!", card, { card = it }, "Capabilities and pricing"); Text("Routing", style = MaterialTheme.typography.titleMedium); SchemaValueEditor(schema, "ModelSettingsInput!", settings, { settings = it }, "Associations"); error?.let { Text(it, color = MaterialTheme.colorScheme.error) }; if (busy) LinearProgressIndicator(Modifier.fillMaxWidth()) } }, confirmButton = { Button(enabled = !busy, onClick = { scope.launch { busy = true; try { val draft = buildJsonObject { put("name", name.trim()); put("modelID", modelId.trim()); put("developer", developer.trim()); put("type", type); put("group", group.trim()); put("icon", icon.trim()); put("remark", remark); put("modelCard", card); put("settings", settings) }; app.gateway.saveModel(initial["id"].text.takeIf(String::isNotBlank), draft, initial ?: JsonNull); app.repository.refresh(); onDismiss() } catch (t: Throwable) { error = t.message } finally { busy = false } } }) { Text("Save") } }, dismissButton = { TextButton(onClick = onDismiss) { Text("Cancel") } })
}

@Composable fun DetailFields(value: JsonElement, keys: List<String>) { Column(verticalArrangement = Arrangement.spacedBy(5.dp)) { keys.forEach { key -> val item = value[key]; if (item !is JsonNull && item.toString().isNotBlank()) { Text(key, style = MaterialTheme.typography.labelMedium); Text(if (item is JsonPrimitive && item.isString) item.text else item.toString(), style = MaterialTheme.typography.bodySmall) } } } }
